---
language: c
matrix:
  include:
    - os: linux
    - os: osx
cache:
  directories:
    - $HOME/.atspkg
install:
  - curl -sSl https://raw.githubusercontent.com/vmchale/atspkg/master/bash/install.sh | bash -s
  - atspkg -V
script:
  - curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s .atsfmt.toml
  - atspkg test -vv
